name: Count All Images and Categories in Repository

on:
  push:
    paths:
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
      - '**.bmp'
      - '**.gif'
      - '.github/workflows/stats.yml'
  workflow_dispatch:

jobs:
  count-sprites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Count all images and categories
        id: count
        run: |
          IMAGE_EXTENSIONS="png jpg jpeg bmp gif"
          TOTAL_IMAGES=0
          CATEGORY_COUNT=0

          # Count all image files recursively (ignore .git, .github and hidden folders)
          for ext in $IMAGE_EXTENSIONS; do
            count=$(find . -type f -iname "*.${ext}" ! -path "./.git/*" ! -path "./.github/*")
            count=$(echo "$count" | wc -l)
            TOTAL_IMAGES=$((TOTAL_IMAGES + count))
          done

          # Count all folders (categories), excluding .git, .github and hidden folders
          CATEGORY_COUNT=$(find . -type d ! -path "./.git*" ! -path "./.github*" ! -path "*/.*" ! -name "." | wc -l)

          # Write stats to stats.json
          echo "{ \"total_sprites\": $TOTAL_IMAGES, \"categories\": $CATEGORY_COUNT }" > stats.json

      - name: Commit and push stats.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update stats.json with global image and category counts
          file_pattern: stats.json
